groups:
  - name: container_alerts
    rules:
      - alert: HighContainerCPUUsage
        expr: (rate(container_cpu_usage_seconds_total{container!="",image!=""}[1m]) * 100) > 5
        for: 30s
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected in {{ $labels.container }}"
          description: "Container {{ $labels.container }} is using high CPU for over 30 seconds."
