groups:
  - name: container_alerts
    rules:
      - alert: HighContainerCPUUsage
        expr: rate(container_cpu_usage_seconds_total{container_label_com_docker_compose_service="app"}[1m]) * 100 > 0.01
        for: 5s
        labels:
          severity: warning
        annotations:
          summary: "High CPU usage detected in {{ $labels.container_label_com_docker_compose_service }}"
          description: "Container {{ $labels.container_label_com_docker_compose_service }} is using high CPU for over 5 seconds."
