name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to Railway
        uses: railwayapp/cli-action@latest
        with:
          command: up
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Run Laravel migrations
        run: |
          sudo apt-get update
          sudo apt-get install -y php php-mbstring php-xml php-bcmath php-mysql unzip curl

          curl -sS https://getcomposer.org/installer | php
          php composer.phar install --no-dev --optimize-autoloader

          cd laravel-app
          php artisan migrate --force